server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver  # 패키지.패키지.패키지.드라이버
    username: cos
    password: cos1234
    url: jdbc:mariadb://localhost:3306/cosdb?serverTimezone=Asia/Seoul  